### ISSUE TITLE
大佬，你 https://henchat.net/ 的验证码系统是不是出问题了？

### ISSUE THREAD

**Issue by crazypeace** [AzusaOu/henChat#4]
大佬，你 https://henchat.net/ 的验证码系统是不是出问题了？

**Comment by CH3COOOH** [comment]
> 大佬，你 https://henchat.net/ 的验证码系统是不是出问题了？

不好意思今天才看见😂现在应该已经好了吧。这个网站偶尔会抽风hh

**Comment by crazypeace** [comment]
:) 好了. 不过忘了是哪篇文 想留什么言了. 哈哈

**Comment by crazypeace** [comment]
https://github.com/CH3COOOH/henChat/assets/665889/8a8fa478-d825-48f6-adb9-37a758b75a7d

**Comment by CH3COOOH** [comment]
我超 怎么又挂了😂

> bandicam.2023-12-18.16-49-06-869.mp4

**Comment by CH3COOOH** [comment]
然后我这边显示的验证码也是bmvTT3。。。

**Comment by CH3COOOH** [comment]
好了我把验证码关了。。一劳永逸地解决了问题😂
